### ISSUE TITLE
Resolve command turns every conditional pin into an explicit pin

### ISSUE THREAD

**Issue by tylerpotts** [Netflix/metaflow-nflx-extensions#25]
Conda pinning syntax enables users to solve environments with various version dependencies as explained here:

https://docs.conda.io/projects/conda-build/en/stable/resources/package-spec.html#package-match-specifications

The [code here](https://github.com/Netflix/metaflow-nflx-extensions/blob/main/metaflow_extensions/netflix_ext/cmd/environment/environment_cmd.py#L616) however sets everything to be an exact pin

This is also causing issues, because this `==` pin is sometimes prepended to other conditional pins such as with the following env:

```yaml
name: test
channels:
  - conda-forge
dependencies:
  - python<3.11
  - pip=23.1
  - pip:
    - click =< 8.1.7
```

This results in the following toml:

```toml
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.conda-lock]
channels = ['conda-forge', 'nodefaults']
allow-pypi-requests = false

[tool.conda-lock.dependencies]
"requests==>=2.21.0" = "*"
"pip==23.1" = "*"
"python==3.11" = "*"

[tool.poetry.dependencies]
"click" = {version = "*",  source="pypi"}
```
